version: '2'

services:
  app:
    container_name: container_spring_app
    build: .
    ports:
      - 8080:8080
  selenium-hub:
    image: selenium/hub
    container_name: 'selenium-hub'
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    container_name: 'chrome'
    links:
      - selenium-hub:hub
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
